// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArh8n5cSCxXx4pO6965Fr7xw1kn4HzvSI',
    appId: '1:48776237975:web:0070aafbb18bba1b45aad2',
    messagingSenderId: '48776237975',
    projectId: 'senmi-94326',
    authDomain: 'senmi-94326.firebaseapp.com',
    storageBucket: 'senmi-94326.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvdhOD0no9ky85rSTU--eMq86cyp2DWPU',
    appId: '1:48776237975:android:3f29c4268521165645aad2',
    messagingSenderId: '48776237975',
    projectId: 'senmi-94326',
    storageBucket: 'senmi-94326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRrF0kw8QZXDr2PLcIPmGRJRkblcXc-rw',
    appId: '1:48776237975:ios:8f254ccb61871f4a45aad2',
    messagingSenderId: '48776237975',
    projectId: 'senmi-94326',
    storageBucket: 'senmi-94326.firebasestorage.app',
    iosBundleId: 'com.example.senmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRrF0kw8QZXDr2PLcIPmGRJRkblcXc-rw',
    appId: '1:48776237975:ios:8f254ccb61871f4a45aad2',
    messagingSenderId: '48776237975',
    projectId: 'senmi-94326',
    storageBucket: 'senmi-94326.firebasestorage.app',
    iosBundleId: 'com.example.senmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArh8n5cSCxXx4pO6965Fr7xw1kn4HzvSI',
    appId: '1:48776237975:web:f0073193238a04ae45aad2',
    messagingSenderId: '48776237975',
    projectId: 'senmi-94326',
    authDomain: 'senmi-94326.firebaseapp.com',
    storageBucket: 'senmi-94326.firebasestorage.app',
  );
}
